name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: read-all

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.mod

      - name: Run tests
        run: go test ./...

  sast:
    name: SAST (gosec)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Run gosec
        uses: securego/gosec@d3b0aabd95f8b0a59cfb5c4b5e02cccfa2dd3882 # v2.22.1
        with:
          args: -fmt sarif -out gosec.sarif ./...

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@ff0a06e83cb2de871e5a09832bc6a81e7276941f # v3
        with:
          sarif_file: gosec.sarif
